"""Optional research strategies built around the stable RLM runtime."""

from rlm0.research.artifacts import ArtifactLimitError, ArtifactRef, ArtifactStore
from rlm0.research.chained import (
    CHAIN_PROTOCOL,
    ChainedArtifactError,
    ChainedExecution,
    ChainedHandoff,
    ChainedLimitError,
    ChainedProtocolError,
    FreshRoot,
    FreshRootFactory,
    HandoffLimits,
    execute_chained,
    parse_handoff,
)
from rlm0.research.contracts import ResearchRun, ResearchStage, ResearchTrial
from rlm0.research.events import (
    EventLog,
    EventRecord,
    EventValidationError,
    ResearchReplay,
    read_events,
    replay,
)
from rlm0.research.optimize import (
    CandidateEvaluation,
    EvaluationBudget,
    EvolutionConfig,
    MetricEstimate,
    OptimizationError,
    OptimizationReport,
    ParetoFrontier,
    PromptCandidate,
    PromptSections,
    RegressionGate,
    Split,
    SplitGuard,
    evolve,
    pareto_frontier,
)
from rlm0.research.srlm import (
    CandidateFactory,
    CandidateSelection,
    SRLMError,
    SRLMResult,
    search,
)
from rlm0.research.verifier import (
    CandidateEvidence,
    RecombinationError,
    RecombinationResult,
    Verification,
    Verifier,
    VerifierVerdict,
    recombine,
)

__all__ = [
    "CHAIN_PROTOCOL",
    "ArtifactLimitError",
    "ArtifactRef",
    "ArtifactStore",
    "CandidateEvaluation",
    "CandidateEvidence",
    "CandidateFactory",
    "CandidateSelection",
    "ChainedArtifactError",
    "ChainedExecution",
    "ChainedHandoff",
    "ChainedLimitError",
    "ChainedProtocolError",
    "EvaluationBudget",
    "EventLog",
    "EventRecord",
    "EventValidationError",
    "EvolutionConfig",
    "FreshRoot",
    "FreshRootFactory",
    "HandoffLimits",
    "MetricEstimate",
    "OptimizationError",
    "OptimizationReport",
    "ParetoFrontier",
    "PromptCandidate",
    "PromptSections",
    "RecombinationError",
    "RecombinationResult",
    "RegressionGate",
    "ResearchReplay",
    "ResearchRun",
    "ResearchStage",
    "ResearchTrial",
    "SRLMError",
    "SRLMResult",
    "Split",
    "SplitGuard",
    "Verification",
    "Verifier",
    "VerifierVerdict",
    "evolve",
    "execute_chained",
    "pareto_frontier",
    "parse_handoff",
    "read_events",
    "recombine",
    "replay",
    "search",
]
